name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'keymap-drawer/**'
      - '.github/workflows/draw-keymap.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: bryanforbes/zmk
          ref: bryanforbes-with-mouse
          path: src
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        id: copy-result
        run: |
          UUID=$(uuidgen)
          cp combined/glove80.uf2 "glove80_${UUID}.uf2"
          echo "uuid=${UUID}" >> "$GITHUB_OUTPUT"
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80_${{ steps.copy-result.outputs.uuid }}.uf2
          path: glove80_${{ steps.copy-result.outputs.uuid }}.uf2
