name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: chrisandreae/zmk
          ref: zephyr-3-2
          path: src

      - name: merge changes from global-quick-tap-ms PR zmkfirmware/zmk#1387
        env:
          owner: zmkfirmware
          repo: zmk
          PR: 1387
        run: |
          cd src
          export GIT_COMMITTER_NAME='Github Action' GIT_AUTHOR_NAME='Github Action'
          curl -SsL -o /tmp/${PR}.patch https://github.com/${owner}/${repo}/pull/${PR}.patch
          git apply -3 < /tmp/${PR}.patch
          git commit -m 'Apply changes from ${owner}/${repo} PR#${PR}'

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        id: copy-result
        run: |
          UUID=$(uuidgen)
          cp combined/glove80.uf2 "glove80_${UUID}.uf2"
          echo "uuid=${UUID}" >> "$GITHUB_OUTPUT"
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80_${{ steps.copy-result.outputs.uuid }}.uf2
          path: glove80_${{ steps.copy-result.outputs.uuid }}.uf2
